!!python/object:tabularbench.utils.config_benchmark_sweep.ConfigBenchmarkSweep
benchmark: !!python/object:tabularbench.data.benchmarks.Benchmark
  dataset_size: !!python/object/apply:tabularbench.core.enums.DatasetSize
  - 10000
  name: !!python/object/apply:tabularbench.core.enums.BenchmarkName
  - numerical_classification
  openml_dataset_ids:
  - 44089
  - 44120
  - 44121
  - 44122
  - 44123
  - 44125
  - 44126
  - 44128
  - 44129
  - 44130
  - 45022
  - 45021
  - 45020
  - 45019
  - 45028
  - 45026
  openml_dataset_names:
  - credit
  - electricity
  - covertype
  - pol
  - house_16H
  - MagicTelescope
  - bank-marketing
  - MiniBooNE
  - Higgs
  - eye_movements
  - Diabetes130US
  - jannis
  - default-of-credit-card-clients
  - Bioresponse
  - california
  - heloc
  task: !!python/object/apply:tabularbench.core.enums.Task
  - classification
config_plotting: !!python/object:tabularbench.utils.config_benchmark_sweep.ConfigPlotting
  benchmark_model_names:
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - MLP
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - Resnet
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - SAINT
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - FT-Transformer
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - RandomForest
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - XGBoost
  - !!python/object/apply:tabularbench.core.enums.ModelName
    - GradientBoostingTree
  confidence_bound: 0.9
  n_random_shuffles: 100
  n_runs: 500
  plot_default_value: true
devices:
- !!python/object/apply:torch.device
  - cuda
  - 0
- !!python/object/apply:torch.device
  - cuda
  - 1
- !!python/object/apply:torch.device
  - cuda
  - 2
- !!python/object/apply:torch.device
  - cuda
  - 3
hyperparams_object:
  attn_dropout: 0.0
  dim: 512
  early_stopping_patience: 40
  linear_attention: true
  lr:
    default: 1.0e-05
    distribution: log_uniform_values
    max: 0.0001
    min: 1.0e-06
  lr_scheduler:
    default: false
    values:
    - true
    - false
  lr_scheduler_patience: 30
  max_epochs: 300
  max_samples_query: 10000
  max_samples_support: 10000
  n_classes: 10
  n_ensembles: 1
  n_features: 100
  n_heads: 4
  n_layers: 12
  name: !!python/object/apply:tabularbench.core.enums.ModelName
  - Foundation
  optimizer: adamw
  path_to_weights: outputs/2024-02-07/13-24-52/weights/model_step_300000.pt
  use_feature_count_scaling: true
  use_pretrained_weights: true
  use_quantile_transformer: true
  weight_decay: 0
  y_as_float_embedding: true
model_name: !!python/object/apply:tabularbench.core.enums.ModelName
- Foundation
model_plot_name: Foundation Pretrain Test
n_default_runs_per_dataset: 10
n_random_runs_per_dataset: 1
openml_dataset_ids_to_ignore:
- 45019
openml_dataset_ids_to_use:
- 44089
- 44120
- 44121
- 44122
- 44123
- 44125
- 44126
- 44128
- 44129
- 44130
- 45020
- 45021
- 45022
- 45026
- 45028
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
- '2024-02-07'
- 13-24-52
- test-numerical-classification
search_type: !!python/object/apply:tabularbench.core.enums.SearchType
- default
seed: 0
