whytrees:
  n_runs: 1000                 # Number of runs to consider for plotting
  n_random_shuffles: 100       # Number of random shuffles for plotting the confidence boundaries
  confidence_bound: 0.90       # Confidence bounds ratio for plotting the confidence boundaries
  plot_default_value: True     # Plot the default value as run #1 

  benchmark_models:   # Which models do we include in all the comparison analysis
    - MLP
    - RESNET
    - SAINT
    - FT_TRANSFORMER
    - RANDOM_FOREST
    - XGBOOST
    - GRADIENT_BOOSTING_TREE

tabzilla:
  benchmark_models:
    - CATBOOST
    - RESNET
    - RANDOM_FOREST
    - SAINT
    - FT_TRANSFORMER
    - XGBOOST
    - NODE
    - SVM
    - MLP_RTDL
    - LIGHTGBM
    - LINEAR_REGRESSION
    - DANET
    - DECISION_TREE
    - MLP
    - STG
    - KNN
    - TABNET
    - VIME