n_features: 100
n_classes: 10
dim: 512
n_layers: 12
n_heads: 4
attn_dropout: 0.0
y_as_float_embedding: True
linear_attention: False

max_samples_support: 8192
max_samples_query: 1024

max_epochs: 300
optimizer: adamw
lr:
  distribution: log_uniform_values
  min: 1.e-6
  max: 1.e-4
  default: 1.e-5
weight_decay: 0
lr_scheduler:
  values: [True, False]
  default: False
lr_scheduler_patience: 30
early_stopping_patience: 40

use_pretrained_weights: True
path_to_weights: outputs_done/foundation_mix_600k_finetune/weights/model_step_600000.pt
n_ensembles: 1

use_quantile_transformer: True
use_feature_count_scaling: True