
parameters: {
    Adult: {
        LinearModel: {},
        KNN: {
            n_neighbors: 25
        },
        DecisionTree: {
            max_depth: 8
        },
        RandomForest: {
            max_depth: 12,
            n_estimators: 85
        },
        XGBoost: {
            max_depth: 5,
            lambda: 0.354,
            alpha: 0.132,
            eta: 0.054
        },
        CatBoost: {
            learning_rate: 0.05,
            max_depth: 8,
            l2_leaf_reg: 0.576
        },
        LightGBM: {
            num_leaves: 24,
            lambda_l2: 1.5e-4,
            lambda_l1: 6.1e-5,
            learning_rate: 2.4e-2
        },
        ModelTree: {
            criterion: gradient-renorm-z,
            max_depth: 3
        },
        MLP: {
            hidden_dim: 47,
            n_layers: 4,
            learning_rate: 8.4e-4
        },
        TabNet: {
            n_d: 14,
            n_steps: 3,
            gamma: 1.76,
            cat_emb_dim: 2,
            n_independent: 3,
            n_shared: 2,
            momentum: 0.319,
            mask_type: entmax
        },
        VIME: {
            p_m: 0.113,
            K: 15,
            alpha: 9.83,
            beta: 0.313
        },
        TabTransformer: {
            dim: 128,
            depth: 1,
            heads: 4,
            weight_decay: -5,
            learning_rate: -5,
            dropout: 0.4
        },
        NODE: {
            num_layers: 4,
            total_tree_count: 1024,
            tree_depth: 8,
            tree_output_dim: 3
        },
        DeepGBM: {
            n_trees: 200,
            maxleaf: 64,
            loss_de: 10,
            loss_dr: 0.7
        },
        RLN: {
            layers: 5,
            theta: -12,
            log_lr: 5,
            norm: 2
        },
        DNFNet: {
            n_forumlas: 1024,
            elastic_net_beta: 1.3
        },
        STG: {
            learning_rate: 4.64e-3,
            lam: 6.2e-3,
            hidden_dims: [500, 50, 10]
        },
        NAM: {
            lr: 1.2e-3,
            output_regularization: 2.95e-3,
            dropout: 1.8e-2,
            feature_dropout: 0.168,
        },
        DeepFM: {
            dnn_dropout: 0.4
        },
        SAINT: {
            dim: 32,
            depth: 1,
            heads: 2,
            dropout: 0.6
        },
        DANet: {
            layer: 8,
            base_outdim: 96,
            k: 4,
            drop_rate: 0
        },
    },
    CaliforniaHousing: {
        LinearModel: { },
        KNN: {
            n_neighbors: 11
        },
        DecisionTree: {
            max_depth: 10
        },
        RandomForest: {
            max_depth: 12,
            n_estimators: 7
        },
        XGBoost: {
            max_depth: 7,
            lambda: 5.47e-4,
            alpha: 0.4515,
            eta: 0.0845
        },
        CatBoost: {
            learning_rate: 0.129,
            max_depth: 12,
            l2_leaf_reg: 17.7
        },
        LightGBM: {
            num_leaves: 34,
            lambda_l2: 1.3e-3,
            lambda_l1: 2.6e-5,
            learning_rate: 7.1e-2
        },
        ModelTree: {
            criterion: gradient-renorm-z,
            max_depth: 3
        },
        MLP: {
            hidden_dim: 68,
            n_layers: 3,
            learning_rate: 9.0e-4
        },
        TabNet: {
            n_d: 43,
            n_steps: 4,
            gamma: 1.22,
            cat_emb_dim: 1,
            n_independent: 5,
            n_shared: 4,
            momentum: 0.235,
            mask_type: entmax
        },
        VIME: {
            p_m: 0.825,
            K: 5,
            alpha: 9.26,
            beta: 0.104
        },
        TabTransformer: {
            dim: 256,
            depth: 6,
            heads: 4,
            weight_decay: -2,
            learning_rate: -3,
            dropout: 0.3
        },
        NODE: {
            num_layers: 2,
            total_tree_count: 2048,
            tree_depth: 6,
            tree_output_dim: 3
        },
        DeepGBM: {
            n_trees: 100,
            maxleaf: 128,
            loss_de: 5,
            loss_dr: 0.9
        },
        RLN: {
            layers: 4,
            theta: -12,
            log_lr: 5,
            norm: 2
        },
        DNFNet: {
            n_forumlas: 1024,
            elastic_net_beta: 1.3
        },
        STG: {
            learning_rate: 1.48e-3,
            lam: 1.87e-3,
            hidden_dims: [ 500, 400, 20 ]
        },
        NAM: {
            lr: 1.14e-3,
            output_regularization: 9.1e-3,
            dropout: 4.22e-3,
            feature_dropout: 0.154,
        },
        DeepFM: {
            dnn_dropout: 0.484
        },
        SAINT: {
            dim: 256,
            depth: 1,
            heads: 2,
            dropout: 0.6
        },
        DANet: {
            layer: 10,
            base_outdim: 96,
            k: 3,
            drop_rate: 0
        },
    },
    Covertype: {
        LinearModel: { },
        KNN: {
            n_neighbors: 41
        },
        DecisionTree: {
            max_depth: 11
        },
        RandomForest: {
            max_depth: 12,
            n_estimators: 48
        },
        XGBoost: {
            max_depth: 12,
            lambda: 0.164,
            alpha: 0.737,
            eta: 0.096
        },
        CatBoost: {
            learning_rate: 0.277,
            max_depth: 12,
            l2_leaf_reg: 1.037
        },
        LightGBM: {
            num_leaves: 56,
            lambda_l2: 0.168,
            lambda_l1: 1.8e-7,
            learning_rate: 0.0318
        },
        ModelTree: {
            criterion: gradient-renorm-z,
            max_depth: 3
        },
        MLP: {
            hidden_dim: 99,
            n_layers: 3,
            learning_rate: 7.0e-4
        },
        TabNet: {
            n_d: 64,
            n_steps: 5,
            gamma: 1.5,
            cat_emb_dim: 1,
            n_independent: 2,
            n_shared: 2,
            momentum: 0.7,
            mask_type: entmax
        },
        VIME: {
            p_m: 0.112,
            K: 20,
            alpha: 2.75,
            beta: 3.24
        },
        TabTransformer: {
            dim: 64,
            depth: 12,
            heads: 8,
            weight_decay: -1,
            learning_rate: -5,
            dropout: 0.4
        },
        NODE: {
            num_layers: 2,
            total_tree_count: 1024,
            tree_depth: 8,
            tree_output_dim: 3
        },
        DeepGBM: {
            n_trees: 100,
            maxleaf: 128,
            loss_de: 5,
            loss_dr: 0.9
        },
        RLN: {
            layers: 8,
            theta: -12,
            log_lr: 5,
            norm: 2
        },
        DNFNet: {
            n_forumlas: 64,
            elastic_net_beta: 1.3
        },
        STG: {
            learning_rate: 2.23e-4,
            lam: 7.07e-3,
            hidden_dims: [ 500, 400, 20 ]
        },
        NAM: {
            lr: 1.14e-3,
            output_regularization: 9.1e-3,
            dropout: 4.22e-3,
            feature_dropout: 0.154,
        },
        DeepFM: {
            dnn_dropout: 0.484
        },
        SAINT: {
            dim: 128,
            depth: 1,
            heads: 2,
            dropout: 0
        }
    }
}