# General parameters
dataset: CaliforniaHousing
model_name: DeepGBM # LinearModel, KNN, SVM, DecisionTree, RandomForest, MLP
                           # XGBoost, CatBoost, LightGBM,
                           # TabNet, VIME, TabTransformer, ModelTree, NODE, DeepGBM, RLN, DNFNet,
                           # STG, NAM, DeepFM, SAINT
objective: regression

# GPU parameters
use_gpu: False
gpu_ids: [0, 1]
data_parallel: True

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221

# Preprocessing parameters
scale: True
target_encode: False

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_features: 8
num_classes: 1 # always one for regression!