# General parameters
dataset: Covertype
model_name: CatBoost # DecisionTree, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM,
    # ModelTree, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: classification # Don't change

# GPU parameters
use_gpu: False
gpu_ids: [0, 1]
data_parallel: True

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: True
target_encode: True

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 7 # for classification
num_features: 54