# General parameters
dataset: HIGGS
model_name: LinearModel # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
                # MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: binary # Don't change

# GPU parameters
use_gpu: True
gpu_ids: [0, 1]
data_parallel: True

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: maximize

# Cross validation parameters
num_splits: 3
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: True
target_encode: False
one_hot_encode: False

# Training parameters
batch_size: 1024
val_batch_size: 1024
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 1  # should be 1 for binary classification
num_features: 28
cat_idx: [27]