hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


defaults:
  - hyperparams/ft_transformer: ft_transformer
  - hyperparams/tabpfn_finetune: tabpfn_zeroshot_10k

continue_last_output: False
output_dir: ${hydra:run.dir}
seed: 0
devices: [6, 7]
runs_per_device: 1
runs_per_dataset: 1000                  # suggested: 500, only for random search
monitor_interval_in_seconds: 10       # plot the results every x seconds

models:
  - tabpfn_finetune
model_plot_names:
  - TabPFN Zeroshot 10k
benchmarks:
  - categorical_classification
  # - numerical_classification
  # - categorical_regression
  # - numerical_regression
  # - categorical_classification_large
  # - numerical_classification_large
  # - categorical_regression_large
  # - numerical_regression_large
search_type:
  # - random
  - default

ignore_datasets:
  # - 44140  # diamonds numerical regression  (missing benchmark values)
  # - 44059  # diamonds categorical regression (missing benchmark values)
  - 44135  # isolet numerical regression (613 features)
  - 44061  # mercedes_benz categorical regression (359 features)
  - 45041  # topo categorical regression (255 features)
  - 45046  # allstate_claims categorical regression (124 features)
  - 45019  # bioresponse numerical classification (419 features)


plotting:
  n_runs: 500                   # Number of runs to consider for plotting
  n_random_shuffles: 100         # Number of random shuffles for plotting the confidence boundaries
  confidence_bound: 0.90       # Confidence bounds ratio for plotting the confidence boundaries

  benchmark_models:   # Based on which models do we normalize the accuracy and R2
    - MLP
    - Resnet
    - SAINT
    - FT Transformer
    - RandomForest
    - XGBoost
    - GradientBoostingTree