hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - hyperparams/ft_transformer: ft_transformer
  - hyperparams/tabpfn: zeroshot_10k
  - hyperparams/foundation: finetune
  - plotting: plotting_default
  # - main_test
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

output_dir: ${hydra:run.dir}
seed: 0
devices: [0, 1, 2, 3, 4, 5, 6, 7]
n_random_runs_per_dataset: 500                  # suggested: 500 
n_default_runs_per_dataset: 10                  # on default we also want multiple runs for the confidence bound

models:
  - FOUNDATION
model_plot_names:
  - FoundationScratch
benchmarks:
  # - DEBUG_CATEGORICAL_CLASSIFICATION
  # - DEBUG_TABZILLA
  - CATEGORICAL_CLASSIFICATION
  - NUMERICAL_CLASSIFICATION
  # - CATEGORICAL_REGRESSION
  # - NUMERICAL_REGRESSION
  # - CATEGORICAL_CLASSIFICATION_LARGE
  # - NUMERICAL_CLASSIFICATION_LARGE
  # - CATEGORICAL_REGRESSION_LARGE
  # - NUMERICAL_REGRESSION_LARGE
  # - TABZILLA_HARD_MAX_TEN_CLASSES
  - TABZILLA_HAS_COMPLETED_RUNS
search_types:
  - DEFAULT
  # - RANDOM


openml_dataset_ids_to_ignore: []
  # - 44140  # diamonds numerical regression  (missing benchmark values)
  # - 44059  # diamonds categorical regression (missing benchmark values)
  # - 44089  # missing SAINT hyperparameter search in original benchmark results
  # - 44135  # isolet numerical regression (613 features)
  # - 44061  # mercedes_benz categorical regression (359 features)
  # - 45041  # topo categorical regression (255 features)
  # - 45046  # allstate_claims categorical regression (124 features)
  # - 45019  # bioresponse numerical classification (419 features)


  