hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


defaults:
  - hyperparams/ft_transformer: ft_transformer
  - _self_




continue_last_output: False
output_dir: ${hydra:run.dir}
seed: 0
devices: [6]
runs_per_device: 1
runs_per_dataset: 1000                  # suggested: 500, only for random search
monitor_interval_in_seconds: 10       # plot the results every x seconds

models:
  - ft_transformer
model_plot_names:
  - FTTrans
benchmarks:
  - categorical_classification
  # - numerical_classification
  # - categorical_regression
  # - numerical_regression
  # - categorical_classification_large
  # - numerical_classification_large
  # - categorical_regression_large
  # - numerical_regression_large
search_type:
  - random
  - default