hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - hyperparams/ft_transformer: ft_transformer
  - hyperparams/tabpfn: finetune_10k
  - hyperparams/foundation: finetune_10k
  - main_test
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

output_dir: ${hydra:run.dir}
seed: 0
devices: [4, 5, 6]
n_random_runs_per_dataset: 500                  # suggested: 500 
n_default_runs_per_dataset: 1                   # on default we also want multiple runs for the confidence bound

models:
  - FOUNDATION
model_plot_names:
  - Foundation Finetune
benchmarks:
  - DEBUG_CATEGORICAL_CLASSIFICATION
  # - CATEGORICAL_CLASSIFICATION
  # - NUMERICAL_CLASSIFICATION
  # - CATEGORICAL_REGRESSION
  # - NUMERICAL_REGRESSION
  # - CATEGORICAL_CLASSIFICATION_LARGE
  # - NUMERICAL_CLASSIFICATION_LARGE
  # - CATEGORICAL_REGRESSION_LARGE
  # - NUMERICAL_REGRESSION_LARGE
  # - TABZILLA_HARD_MAX_TEN_CLASSES
search_types:
  - DEFAULT
  # - RANDOM


openml_dataset_ids_to_ignore: []
  # - 44140  # diamonds numerical regression  (missing benchmark values)
  # - 44059  # diamonds categorical regression (missing benchmark values)
  # - 44089  # missing SAINT hyperparameter search in original benchmark results
  # - 44135  # isolet numerical regression (613 features)
  # - 44061  # mercedes_benz categorical regression (359 features)
  # - 45041  # topo categorical regression (255 features)
  # - 45046  # allstate_claims categorical regression (124 features)
  # - 45019  # bioresponse numerical classification (419 features)


plotting:
  n_runs: 1000                 # Number of runs to consider for plotting
  n_random_shuffles: 100       # Number of random shuffles for plotting the confidence boundaries
  confidence_bound: 0.90       # Confidence bounds ratio for plotting the confidence boundaries
  plot_default_value: True     # Plot the default value as run #1 

  benchmark_models:   # Based on which models do we normalize the accuracy and R2
    - MLP
    - RESNET
    - SAINT
    - FT_TRANSFORMER
    - RANDOM_FOREST
    - XGBOOST
    - GRADIENT_BOOSTING_TREE