# @package _global_

optim:
  max_steps: 500_000                # Every step completes batch_size * gradient_accumulation_steps samples
  warmup_steps: 10_000
  eval_every_n_steps: 10_000
  batch_size: 4                     # Total batch size over all devices. 
  gradient_accumulation_steps: 1   # Accumulation steps are not counted towards max_steps
  lr: 1.e-5
  cosine_scheduler: False  
  use_pretrained_weights: True
  path_to_weights: outputs_done/foundation_key_att/weights/model_step_500000.pt               # Path to a checkpoint to load weights from

data:
  min_samples_support: 128
  max_samples_support: 8192            
  n_samples_query: 2048