# @package _global_
workers_per_gpu: 4

optim:
  max_steps: 80              
  eval_every_n_steps: 50

hyperparams:
  foundation:
    max_epochs: 2

testing:
  n_default_runs_per_dataset_test: 1    
  benchmarks:
    - DEBUG_CATEGORICAL_CLASSIFICATION
    - DEBUG_TABZILLA
    # - CATEGORICAL_CLASSIFICATION
    # - NUMERICAL_CLASSIFICATION
    # - CATEGORICAL_REGRESSION
    # - NUMERICAL_REGRESSION
    # - CATEGORICAL_CLASSIFICATION_LARGE
    # - NUMERICAL_CLASSIFICATION_LARGE
    # - CATEGORICAL_REGRESSION_LARGE
    # - NUMERICAL_REGRESSION_LARGE
    # - TABZILLA_HARD_MAX_TEN_CLASSES
    # - TABZILLA_HAS_COMPLETED_RUNS