hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - hyperparams/ft_transformer: ft_transformer

output_dir: ${hydra:run.dir}
seed: 0
devices: [0, 1, 2, 3, 4, 5, 6, 7]


model:
  dim: 64
  n_layers: 8
  heads: 4
  attn_dropout: 0.1
  ff_dropout: 0.1

optim:
  max_steps: 100000
  log_every_n_steps: 100
  eval_every_n_steps: 1000
  batch_size: 8
  lr: 1.e-4
  weight_decay: 0.00
  beta1: 0.9
  beta2: 0.99
  warmup_steps: 1000
  cosine_scheduler: False  

data:
  min_samples: 100
  max_samples: 1000      # Support + query
  min_features: 3
  max_features: 100
  max_classes: 10
  support_proportion: 0.8   # Proportion of support samples vs query samples


plotting:
  n_runs: 500                   # Number of runs to consider for plotting
  n_random_shuffles: 100         # Number of random shuffles for plotting the confidence boundaries
  confidence_bound: 0.90       # Confidence bounds ratio for plotting the confidence boundaries
  plot_default_value: True     # Plot the default value of the model

  benchmark_models:   # Based on which models do we normalize the accuracy and R2
    - MLP
    - RESNET
    - SAINT
    - FT_TRANSFORMER
    - RANDOM_FOREST
    - XGBOOST
    - GRADIENT_BOOSTING_TREE