hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


continue_last_output: False
output_dir: ${hydra:run.dir}
seed: 0
devices: [0]
runs_per_device: 2
runs_per_dataset: 3                    # suggested: 500
monitor_interval_in_seconds: 100       # plot the results every x seconds

models:
  - mlp
  - ft_transformer
model_plot_names:
  - piecewise_linear
  - ft_transformer_2
benchmarks:
  - categorical_classification
  # - numerical_classification
  # - categorical_regression
  # - numerical_regression
random_search:
  - True
  # - False