hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


continue_last_output: True
output_dir: ${hydra:run.dir}
seed: 0
devices: [6, 7]
runs_per_device: 4
runs_per_dataset: 3                   # suggested: 500
monitor_interval_in_seconds: 10       # plot the results every x seconds

models:
  - mlp_pwl
  - ft_transformer
model_plot_names:
  - piecewise_linear
  - ft_transformer_2
benchmarks:
  - categorical_classification
  # - numerical_classification
  # - categorical_regression
  # - numerical_regression
random_search:
  - True
  # - False