hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}


output_dir: ${hydra:run.dir}
seed: 0
devices: [6, 7]
runs_per_device: 2
runs_per_dataset: 3      # minimum 100 required to show up in the plots

models:
  - mlp
  - ft_transformer
model_plot_names:
  - piecewise_linear
  - ft_transformer_2
benchmarks:
  - categorical_classification
  # - numerical_classification
  # - categorical_regression
  # - numerical_regression
random_search:
  - True
  # - False