!!python/object:tabularbench.config.config_benchmark_sweep.ConfigBenchmarkSweep
benchmark: !!python/object:tabularbench.data.benchmarks.Benchmark
  dataset_size: !!python/object/apply:tabularbench.core.enums.DatasetSize
  - 10000
  name: !!python/object/apply:tabularbench.core.enums.BenchmarkName
  - categorical_classification
  openml_dataset_ids:
  - 44156
  - 44157
  - 44159
  - 45035
  - 45036
  - 45038
  - 45039
  origin: !!python/object/apply:tabularbench.core.enums.BenchmarkOrigin
  - whytrees
  task: !!python/object/apply:tabularbench.core.enums.Task
  - classification
devices:
- !!python/object/apply:torch.device
  - cuda
  - 0
- !!python/object/apply:torch.device
  - cuda
  - 1
- !!python/object/apply:torch.device
  - cuda
  - 2
- !!python/object/apply:torch.device
  - cuda
  - 3
- !!python/object/apply:torch.device
  - cuda
  - 4
- !!python/object/apply:torch.device
  - cuda
  - 5
- !!python/object/apply:torch.device
  - cuda
  - 6
- !!python/object/apply:torch.device
  - cuda
  - 7
hyperparams_object:
  attn_dropout: 0.0
  dim: 512
  early_stopping_patience: 40
  linear_attention: false
  lr:
    default: 1.0e-05
    distribution: log_uniform_values
    max: 0.0001
    min: 1.0e-06
  lr_scheduler:
    default: false
    values:
    - true
    - false
  lr_scheduler_patience: 30
  max_epochs: 300
  max_samples_query: 1024
  max_samples_support: 8192
  n_classes: 10
  n_ensembles: 1
  n_features: 100
  n_heads: 4
  n_layers: 12
  optimizer: adamw
  path_to_weights: outputs_done/foundation_forest_big_300k/weights/model_step_300000.pt
  use_feature_count_scaling: true
  use_pretrained_weights: true
  use_quantile_transformer: true
  weight_decay: 0
  y_as_float_embedding: true
model_name: !!python/object/apply:tabularbench.core.enums.ModelName
- Foundation
model_plot_name: TabSGFD-Finetune
n_default_runs_per_dataset: 10
n_random_runs_per_dataset: 500
openml_dataset_ids_to_ignore: []
openml_dataset_ids_to_use:
- 44156
- 44157
- 44159
- 45035
- 45036
- 45038
- 45039
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
- '2024-03-24'
- 18-42-54
- foundation-default-categorical_classification
plotting: !!python/object:tabularbench.config.config_plotting.ConfigPlotting
  tabzilla: !!python/object:tabularbench.config.config_plotting.ConfigPlottingTabzilla
    benchmark_model_names:
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - CatBoost
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - Resnet
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - RandomForest
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - SAINT
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - FT-Transformer
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - XGBoost
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - NODE
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - SVM
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - MLP-rtdl
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - LightGBM
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - LinearRegression
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - DANet
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - DecisionTree
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - MLP
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - STG
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - KNN
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - TabNet
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - VIME
  whytrees: !!python/object:tabularbench.config.config_plotting.ConfigPlottingWhytrees
    benchmark_model_names:
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - MLP
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - Resnet
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - SAINT
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - FT-Transformer
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - RandomForest
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - XGBoost
    - !!python/object/apply:tabularbench.core.enums.ModelName
      - GradientBoostingTree
    confidence_bound: 0.9
    n_random_shuffles: 100
    n_runs: 1000
    plot_default_value: true
search_type: !!python/object/apply:tabularbench.core.enums.SearchType
- default
seed: 0
