max_samples_support: 8192
max_samples_query: 1024
n_features: 100

max_epochs: 300
optimizer: adamw
lr:
  distribution: log_uniform_values
  min: 1.e-6
  max: 1.e-4
  default: 1.e-5
weight_decay: 0
lr_scheduler:
  values: [True, False]
  default: False
lr_scheduler_patience: 30
early_stopping_patience: 40

use_pretrained_weights: True
path_to_weights: tabularbench/models/tabPFN/prior_diff_real_checkpoint_n_0_epoch_42.cpkt
n_ensembles: 1

use_quantile_transformer: True
use_feature_count_scaling: True