dataset: 'epsilon'
task: 'classification'
train_ratio: 1.0
resume_dir: ''
logname: 'layer32'

fit:
  max_epochs: 1500
  patience: 500
  lr: 0.02

model:
  layer: 32
  base_outdim: 96
  k: 8
  drop_rate: 0.1