wandb_version: 1

data__keyword:
  value: wine
data__method_name:
  value: real_data
model__learning_rate:
  value: 0.07947901529553753
model__loss:
  value: exponential
model__max_depth:
  value: null
model__min_samples_leaf:
  value: 4
model__min_samples_split:
  value: 2
model__n_estimators:
  value: 61
model__subsample:
  value: 0.6900091654039056
model_name:
  value: gbt_c
model_type:
  value: sklearn
n_iter:
  value: auto
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transform__1__max_rel_decrease:
  value: 0.02
transform__1__method_name:
  value: remove_useless_features
transform__1__n_iter:
  value: 3
transform__2__cov_mult:
  value: 0.1
transform__2__method_name:
  value: remove_high_frequency
