wandb_version: 1

data__keyword:
  value: california
data__method_name:
  value: real_data
model__learning_rate:
  value: 0.011960038569789343
model__loss:
  value: deviance
model__max_depth:
  value: 2
model__min_samples_leaf:
  value: 30
model__min_samples_split:
  value: 2
model__n_estimators:
  value: 559
model__subsample:
  value: 0.9104458183755284
model_name:
  value: gbt_c
model_type:
  value: sklearn
n_iter:
  value: auto
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transform__1__max_rel_decrease:
  value: 0.02
transform__1__method_name:
  value: remove_useless_features
transform__1__n_iter:
  value: 3
transform__2__cov_mult:
  value: 0.01
transform__2__method_name:
  value: remove_high_frequency
